apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: default
type: Opaque
data:
  user: "cG9zdGdyZXM=" #postgres as base64 encoded string
  password: "cG9zdGdyZXM=" #postgres as base64 encoded string
